---
# tasks file for gitlab-runner
- name: 清除旧数据及旧容器
  shell: 'rm -rf /opt/gengxiankun-galaxy/gitlab-runner/docker-compose-{{ GITLAB_RUNNER_NAME }}.yaml;
  docker rm -f {{ GITLAB_RUNNER_NAME }}'
  ignore_errors: yes

- name: 预处理
  shell: '[[ ! -d "/opt/gengxiankun-galaxy/gitlab-runner" ]] && mkdir -vp /opt/gengxiankun-galaxy/gitlab-runner'
  ignore_errors: yes

- name: 配置相关参数
  template: src=docker-compose.yaml.j2 dest=/opt/gengxiankun-galaxy/gitlab-runner/docker-compose-{{ GITLAB_RUNNER_NAME }}.yaml

- name: run docker-compose
  shell: "docker-compose -f /opt/gengxiankun-galaxy/gitlab-runner/docker-compose-{{ GITLAB_RUNNER_NAME }}.yaml up -d"

- name: 注册 gitlab-runner
  shell: "docker exec -t {{ GITLAB_RUNNER_NAME }} gitlab-runner register \
  --non-interactive \
  --executor 'docker' \
  --docker-image {{ GITLAB_RUNNER_DOCKER_IMAGE }} \
  --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
  --url '{{ GITLAB_EXTERNAL_URL }}' \
  --registration-token '{{ GITLAB_PROJECT_REGISTRATION_TOKEN }}' \
  --description '{{ GITLAB_RUNNER_NAME }}' \
  --tag-list 'docker' \
  --run-untagged \
  --locked='false'"
